### ISSUE TITLE
Make powerbroker on AWS use private IPs

### ISSUE THREAD

**Issue by alaric-dotmesh** [dotmesh-io/dotscience-tf#14]
As a dotscience administrator, I want my runners to not have public IPs with access to the Docker socket, so that I can keep them safe and secure from external threats.

Therefore, I'd like to restrict access to the docker socket to just the Hub so PB can connect and start the runner container, and have PB use the private IP rather than trying to allocate and use a public IP for the runner VMs.

**Comment by alaric-dotmesh** [comment]
Proposed fix:

local-stack change: https://github.com/dotmesh-io/local-stack/pull/51
dotscience-tf change: https://github.com/dotmesh-io/dotscience-tf/pull/15
dotscience-images change to pull in local-stack: https://github.com/dotmesh-io/dotscience-images/pull/74

**Comment by rusenask** [comment]
just to clarify - this is nothing to do with "safe and secure", Docker API uses TLS client cert authentication

**Comment by alaric-dotmesh** [comment]
> just to clarify - this is nothing to do with "safe and secure", Docker API uses TLS client cert authentication

That's assuming there's no bugs in the TLS server implementation that allow the certificate to be bypassed, or the daemon just rooted outright through some silliness! Defence in depth!

**Comment by alaric-dotmesh** [comment]
(TLS is an awfully complicated protocol, and there's plenty of precedent of TLS implementations being buggy)
