### ISSUE TITLE
Default runner created when user first signs up comes up with incorrect image.

### ISSUE THREAD

**Issue by prisamuel** [dotmesh-io/dotscience-tf#40]
Rather than picking up dotscience-cpu-runner image, this comes up with `"ami-f90a4880"`

**Comment by itamarst** [comment]
`ami-f90a4880` comes from power-broker, specifically driver/amazon/util.go's `defaultImage()` function.

**Comment by itamarst** [comment]
GCP has in theory infrastructure for overriding runner image: startup.go takes a command-line argument (--gcp-runner-machine-image and related options), which then sets an environment variable (`PB_GOOGLE_MACHINE_IMAGE` and friends), which are then passed to powerbroker via `docker-compose.pb.yml` in `local-stack`.

In practice, it doesn't seem like this is used; you'll notice the script in this repository that calls ds-startup doesn't use that particular --gcp option.

AWS could in theory have all the above, but it doesn't. So would need to add appropriate environment variables, expose them from startup.go's command-line options, and then populate from the terraform.tfvars list of AMIs.

**Comment by itamarst** [comment]
The environment variable to set is `PB_AMAZON_IMAGE`.

**Comment by rusenask** [comment]
I thought this was disabled altogether when using terraform?

**Comment by itamarst** [comment]
What do you mean by "this"? There is no env var set, so AFAICT it defaults to the values hardcoded in the code.

**Comment by itamarst** [comment]
Apparently not a problem anymore.
