### ISSUE TITLE
Rate limit problem on letsencrypt

### ISSUE THREAD

**Issue by binocarlos** [dotmesh-io/dotscience-tf#57]
A user put an expired licence into inputs.tfvars - the gateway failed to start (because the licence was wrong).

We then updated to a working licence - the gateway got stuck in a lets encrypt rate limit problem.

We need to make sure that let's encrypt certs are not requested until the gateway is confirmed as up and running.

**Comment by rusenask** [comment]
you have some other issue as we check license before we do anything else: https://github.com/dotmesh-io/gateway/blob/master/cmd/gateway/main.go#L77-L90. Server with let's encrypt challenge is started a lot later
